<a href="https://colab.research.google.com/github/chw8207/numpy/blob/main/%EB%B0%B0%EC%97%B4%EA%B5%AC%EC%A1%B0_%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 깃허브 연동

In [1]:
cd /content/drive/MyDrive/Colab Notebooks/numpy/numpy_study

/content/drive/MyDrive/Colab Notebooks/numpy/numpy_study


In [3]:
! git clone https://chw8207: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@github.com/chw8207/numpy.git

Cloning into 'numpy'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 1.43 KiB | 22.00 KiB/s, done.


### 리스트 구조

In [4]:
l = [[1,2,3],[4,5,6]]

In [5]:
type(l)

list

In [6]:
# 원소 조회
l[0]

[1, 2, 3]

In [7]:
l[1]

[4, 5, 6]

In [8]:
# enumerate : 인덱스, 원소 가져오기
for i, a in enumerate(l) : 
  for j, b in enumerate(a) : 
    print(l[i][j])

1
2
3
4
5
6


In [9]:
import numpy as np

In [10]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [11]:
# 클래스 이름 조회하기 : __name__
np.ndarray.__name__

'ndarray'

In [12]:
type(np.ndarray.var)

method_descriptor

In [ ]:
# 다차원 배열 클래스에 정의된 속성이나 메소드를 확인하기 위해
# 이름공간(namespace) 확인하기
for i in dir(np.ndarray) : 
  if not i.startswitch('_') : 
    if type(np.ndarray.__dict__[i]) != type(np.ndarray.var) : 
      print(i)

#### 넘파이 배열 생성하기(리스트)

In [16]:
l = [1,2,3,4]

In [18]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [19]:
type(a)

numpy.ndarray

### 넘파이 배열 생성하기(튜플)

In [21]:
t = (1,2,3,4)

(1, 2, 3, 4)

In [22]:
b = np.array(t)
b

array([1, 2, 3, 4])

In [23]:
type(b)

numpy.ndarray

In [24]:
# data : 메모리에 저장된 레퍼런스 출력
a.data

In [25]:
# obj로 참조하면 다차원 배열의 값을 보여줌.
a.data.obj

array([1, 2, 3, 4])

In [26]:
type(a.data.obj)

numpy.ndarray

In [28]:
# base : 원본 레퍼런스를 저장함
c = b
c.base is b.base

True

In [29]:
# 원본 배열 변경하기
c[0] = 100
c

array([100,   2,   3,   4])

In [30]:
b

array([100,   2,   3,   4])

### 다차원 배열을 복사해서 새로운 배열 만들기

In [32]:
d = np.array(b)
d[0] = 99

d

array([99,  2,  3,  4])

In [33]:
b

array([100,   2,   3,   4])