<a href="https://colab.research.google.com/github/chw8207/numpy/blob/main/%EB%B0%B0%EC%97%B4%EA%B5%AC%EC%A1%B0_%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 깃허브 연동

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/numpy/numpy_study

/content/drive/MyDrive/Colab Notebooks/numpy/numpy_study


In [ ]:
! git clone https://chw8207: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@github.com/chw8207/numpy.git

Cloning into 'numpy'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), 1.43 KiB | 22.00 KiB/s, done.


### 리스트 구조

In [ ]:
l = [[1,2,3],[4,5,6]]

In [ ]:
type(l)

list

In [ ]:
# 원소 조회
l[0]

[1, 2, 3]

In [ ]:
l[1]

[4, 5, 6]

In [ ]:
# enumerate : 인덱스, 원소 가져오기
for i, a in enumerate(l) : 
  for j, b in enumerate(a) : 
    print(l[i][j])

1
2
3
4
5
6


In [ ]:
import numpy as np

In [ ]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [ ]:
# 클래스 이름 조회하기 : __name__
np.ndarray.__name__

'ndarray'

In [ ]:
type(np.ndarray.var)

method_descriptor

In [ ]:
# 다차원 배열 클래스에 정의된 속성이나 메소드를 확인하기 위해
# 이름공간(namespace) 확인하기
for i in dir(np.ndarray) : 
  if not i.startswitch('_') : 
    if type(np.ndarray.__dict__[i]) != type(np.ndarray.var) : 
      print(i)

#### 넘파이 배열 생성하기(리스트)

In [ ]:
l = [1,2,3,4]

In [ ]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

### 넘파이 배열 생성하기(튜플)

In [ ]:
t = (1,2,3,4)

(1, 2, 3, 4)

In [ ]:
b = np.array(t)
b

array([1, 2, 3, 4])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
# data : 메모리에 저장된 레퍼런스 출력
a.data

In [ ]:
# obj로 참조하면 다차원 배열의 값을 보여줌.
a.data.obj

array([1, 2, 3, 4])

In [ ]:
type(a.data.obj)

numpy.ndarray

In [ ]:
# base : 원본 레퍼런스를 저장함
c = b
c.base is b.base

True

In [ ]:
# 원본 배열 변경하기
c[0] = 100
c

array([100,   2,   3,   4])

In [ ]:
b

array([100,   2,   3,   4])

### 다차원 배열을 복사해서 새로운 배열 만들기

In [ ]:
d = np.array(b)
d[0] = 99

d

array([99,  2,  3,  4])

In [ ]:
b

array([100,   2,   3,   4])

### float형 다차원 배열 만들기

In [ ]:
e = np.array(l, dtype=np.float)
e

<ipython-input-34-13771441d24d>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  e = np.array(l, dtype=np.float)


array([1., 2., 3., 4.])

In [ ]:
e.dtype

dtype('float64')

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [ ]:
# 차원 확인
a2.ndim

2

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.itemsize

8

In [ ]:
a2.size

6

### strides
- 행을 기준으로 내부의 1차원 배열을 원소로 관리함
- (하나 행의 전체 길이, 1차원 배열의 원소 하나의 길이)

In [ ]:
a2.strides

(24, 8)

In [ ]:
# flatten
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# ravel() : 내부 데이터 그대로 반환
a2.ravel()

array([1, 2, 3, 4, 5, 6])

### 넘파이 배열 원소 조회하기

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
l

[1, 2, 3, 4]

In [ ]:
print(a[0], l[0])

1 1


In [ ]:
# 다차원 배열 생성
l2 = [[1,2,3],[4,5,6]]
l2

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 리스트의 원소 조회하기
try : 
  l2[0,1]
except Exception as e : 
  print(e)

list indices must be integers or slices, not tuple


In [ ]:
l2[0][1]

2

In [ ]:
# 배열의 원소 조회하기
a2[0,1]

2

In [ ]:
type(a2[0,1])

numpy.int64

In [ ]:
a2[0,1].item()

2

In [ ]:
type(a2[0,1].item())

int

In [ ]:
# real : 실수까지 관리
# imag : 허수를 관리
a2[0,1].real

2

In [ ]:
a2[0,1].imag

0

### 넘파이 모듈의 배열 내부구조 확인

In [2]:
import numpy as np
na = np.array([[[1,2,3,],[4,5,6]],[[1,2,3,],[4,5,6]]])
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [3]:
na.ndim

3

In [4]:
na.shape

(2, 2, 3)

In [5]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
na[0].shape

(2, 3)

In [7]:
# 스페셜 속성 : __array_interface__
na.__array_interface__

{'data': (140138407972032, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (2, 2, 3),
 'version': 3}

In [8]:
na.strides

(48, 24, 8)

In [10]:
# 스페셜 속성에서 내부 원소 검색은 대괄호에 키를 문자열로 전달
na.__array_interface__['data'][0]

140138407972032

In [14]:
# data속성의 데이터를 확인 : tobytes()
len(na.data.tobytes())

96

In [16]:
# 다차원 배열 리스트로 변환하기 : tolist()
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

### data 속성 관리기준

In [19]:
# 1차원 배열 만들기
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:
a.data

In [23]:
# 파이썬 memoryview 클래스에 1차원 배열을 인자로 전달
# 메모리의 로딩하는 객체를 만들고 변수에 할당
mem = memoryview(a)
mem

In [24]:
# 원소조회하기
a.data[0]

1

In [25]:
# 모든 정보 조회하기 : obj
a.data.obj

array([1, 2, 3, 4])

In [26]:
# obj속성에서 원소 조회
a.data.obj[0]

1

In [27]:
a.dtype

dtype('int64')

In [28]:
# 원소의 길이 확인하기
a.itemsize

8

In [29]:
# 배열의 원소 16진수로 변환 : hex()
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [30]:
# 더 큰 수를 가진 배열 만들기
b = np.array([999,9999,99999,999999])
b

array([   999,   9999,  99999, 999999])

In [32]:
# data속성 내의 값을 16진수로 표기
# 8개의 문자를 출력(슬라이싱 통해)
b.data.hex()[:8]

'e7030000'

In [33]:
hex(999)

'0x3e7'

In [34]:
int('0x3e7',16)

999

In [35]:
# 16진수로 표시할 때 
# 몫과 나머지를 같이 구하는 divmod() 사용
divmod(999,16)

(62, 7)

In [36]:
divmod(62,16)

(3, 14)

In [37]:
divmod(3,16)

(0, 3)

In [38]:
# 배열 전체의 크기 확인하기
a.size

4

In [39]:
# 반복문 활용하여 다차원 배열의 원소를 하나씩 출력하기
for i in range(a.size) : 
  print(a[i])

1
2
3
4


In [42]:
# flat속성 사용해서 편한 방법으로 순환하기
# flat속성 : 하나의 반복자 제공
a.flat

In [45]:
for i in a.flat : 
  print(i)

1
2
3
4


In [46]:
# frombuffer() : 다차원배열을 복사하지 않고 공유
c = np.array([1,2,3,4], dtype=np.float_)
c

array([1., 2., 3., 4.])

In [47]:
x = np.frombuffer(c)
x

array([1., 2., 3., 4.])

In [48]:
# 배열의 자료형 확인하기
# 하나의 원소는 8비트 단위로 관리
x.dtype

dtype('float64')

In [49]:
x[0]

1.0

In [50]:
# flags : 배열의 정보들을 관리하는 정보 확인
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [51]:
x.base is c

True

In [53]:
# 원본 배열 c
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False